### ISSUE TITLE
Create a 404 page

### ISSUE THREAD

**Issue by N3v1** [N3v1/QuickConvertt#24]
Hi everyone,
I could use some help to create a 404 page 

You can create a 404.html or something like that in the pages/html folder. Please create the stylesheets in the style/ folder

**Comment by Bashamega** [comment]
Assign me please, but send me the design you want

**Comment by N3v1** [comment]
> Assign me please, but send me the design you want

Thanks, @Bashamega. I will finish the design by Friday since I have a lot to do next week.
